wordyar/accounts/urls.py
from argparse import Namespace
from unicodedata import name
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("register/", views.UserRegister.as_view(), name="register"),
    path("login/", views.Login.as_view(), name="login"),
    path("logout/", views.Logout.as_view(), name="logout"),
    path("profile/", views.Profile.as_view(), name="profile"),
]

wordyar/core/urls.py
from django.urls import path
from .views import home


app_name = "core"

urlpatterns = [
    path("", home.as_view(), name="home")
]

wordyar/wordyar/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls", namespace="core")),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('exams/', include("exams.urls", namespace="exams")),
]

wordyar/templates/inc/messages.html
{% if messages %}
    {% for message in messages %}
        <p class="alert alert-{{message.tags}}">{{ message }}</p>
    {% endfor %}
{% endif %}

wordyar/templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class= "navbar-nav">
        <a class="nav-link active" href="{% url 'core:home' %}">خانه</a>
    </div>
    <div class="navbar-nav mr-auto"> 
        {% if request.user.is_authenticated %}
        <a class="nav-link active" href="{% url 'accounts:profile' %}">نام کاربری: {{ request.user.username }}</a>
        <a class="nav-link active" href="{% url 'accounts:logout' %}"> خروج </a>
        {% else %}
        <a class="nav-link active" href="{% url 'accounts:register' %}">ثبت نام</a>
        <a class="nav-link active" href="{% url 'accounts:login' %}"> ورود </a>
        {% endif %}
    </div>

</nav>